name: Update List

on:
  schedule:
    - cron: '0 12 * * *' # Executa todos os dias ao meio-dia (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Baixar as listas e limpar comentários
        run: |
          curl -s "${{ vars.LIST_URL_1 }}" | grep -v '^#' > raw_domains.txt
          curl -s "${{ vars.LIST_URL_2 }}" | grep -v '^#' >> raw_domains.txt
          curl -s "${{ vars.LIST_URL_3 }}" | grep -v '^#' >> raw_domains.txt

      - name: Validar domínios
        run: |
          grep -E '^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$' raw_domains.txt > valid_domains.txt

      - name: Processar lista e adicionar ctag
        run: |
          awk '{print "||"$1"^$ctag=user_admin"}' valid_domains.txt > domains.txt

      - name: Remover domínios duplicados
        run: |
          sort -u domains.txt -o domains.txt

      - name: Verificar mudanças
        id: check_changes
        run: |
          if ! git diff --exit-code domains.txt; then
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit e push das mudanças
        if: env.CHANGES == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add domains.txt
          git commit -m "Release $(date +'%Y/%m/%d')"  # Commit com data no formato YYYY/MM/DD
          git push

      - name: Clean old commits
        run: |
          curl -fsSL -o bfg.jar https://repo1.maven.org/maven2/com/madgag/bfg/1.15.0/bfg-1.15.0.jar && \
          git clone --mirror https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo && \
          java -jar bfg.jar --strip-blobs-bigger-than 10K -fs 100M repo && \
          cd repo && \
          git reflog expire --expire=now --all && \
          git gc --prune=now --aggressive && \
          git push origin --force || echo
          cd ../ && rm -rf repo

      - name: Git init
        run: |
          sleep 12
          git clone --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo && cd repo && \
          git checkout --orphan TEMP && \
          git add -A && \
          git config user.name "Nel [bot]" && \
          git config user.email '<>' && \
          git commit -am "Release $(date +'%Y/%m/%d')"  # Commit com data no formato YYYY/MM/DD
          git branch -D main && \
          git branch -m main && \
          git push -f origin main && \
          cd ../ && rm -rf repo

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
          token: ${{ secrets.GITHUB_TOKEN }}
